# Project: Chapter3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = test.o practice_1.o
LINKOBJ  = test.o practice_1.o
LIBS     = -L"D:/Dev-C++/Dev-Cpp/MinGW64/lib" -L"D:/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Dev-C++/Dev-Cpp/MinGW64/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-C++/Dev-Cpp/MinGW64/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Chapter3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

test.o: test.cpp
	$(CPP) -c test.cpp -o test.o $(CXXFLAGS)

practice_1.o: practice_1.cpp
	$(CPP) -c practice_1.cpp -o practice_1.o $(CXXFLAGS)
